spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

      org:
        hibernate:
          envers:
#            audit_table_prefix: xaudit_
#            audit_table_suffix: ""

  mysql:
    host: jdbc:mysql://localhost:3306/dissertation?serverTimezone=UTC
    login: root
    pass: root
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    driverClassName: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: 'http://localhost:8181'

springdoc:
  packagesToScan: pl.pwr.dissertation.api.controller
  pathsToMatch: /**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: false


logger: DEBUG
#  org:
#    hibernate:
#      sql: DEBUG
